<?php

namespace App\Listeners;

use App\Events\CommunityPostCreated;
use App\Models\CommunityPost;
use App\Services\WebPushService;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class SendCommunityPostNotification implements ShouldQueue
{
    use InteractsWithQueue;

    public int $tries = 3;

    /**
     * Create the event listener.
     */
    public function __construct(private WebPushService $webPushService)
    {
        //
    }

    /**
     * Handle the event.
     */
    public function handle(CommunityPostCreated $event): void
    {
        // $event->post is an array generated by broadcastWith(), not the model instance
        // We need to fetch the original model for WebPushService
        $postModel = CommunityPost::find($event->post['id'] ?? null);

        if ($postModel) {
            $this->webPushService->notifyCommunityPost($postModel);
        }
    }
}
